// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evmstorechain/evmstorechain/blockstoragestate.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Blockstoragestate struct {
	Blocknumber string `protobuf:"bytes,1,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	State       uint64 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *Blockstoragestate) Reset()         { *m = Blockstoragestate{} }
func (m *Blockstoragestate) String() string { return proto.CompactTextString(m) }
func (*Blockstoragestate) ProtoMessage()    {}
func (*Blockstoragestate) Descriptor() ([]byte, []int) {
	return fileDescriptor_81c8e17d6c6128ee, []int{0}
}
func (m *Blockstoragestate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Blockstoragestate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Blockstoragestate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Blockstoragestate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blockstoragestate.Merge(m, src)
}
func (m *Blockstoragestate) XXX_Size() int {
	return m.Size()
}
func (m *Blockstoragestate) XXX_DiscardUnknown() {
	xxx_messageInfo_Blockstoragestate.DiscardUnknown(m)
}

var xxx_messageInfo_Blockstoragestate proto.InternalMessageInfo

func (m *Blockstoragestate) GetBlocknumber() string {
	if m != nil {
		return m.Blocknumber
	}
	return ""
}

func (m *Blockstoragestate) GetState() uint64 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Blockstoragestate)(nil), "evmstorechain.evmstorechain.Blockstoragestate")
}

func init() {
	proto.RegisterFile("evmstorechain/evmstorechain/blockstoragestate.proto", fileDescriptor_81c8e17d6c6128ee)
}

var fileDescriptor_81c8e17d6c6128ee = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0x2d, 0xcb, 0x2d,
	0x2e, 0xc9, 0x2f, 0x4a, 0x4d, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x47, 0xe5, 0x25, 0xe5, 0xe4, 0x27,
	0x67, 0x83, 0xf8, 0x89, 0xe9, 0xa9, 0xc5, 0x25, 0x89, 0x25, 0xa9, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0xd2, 0x28, 0xca, 0xf4, 0x50, 0x78, 0x4a, 0xde, 0x5c, 0x82, 0x4e, 0xe8, 0xfa, 0x84,
	0x14, 0xb8, 0xb8, 0xc1, 0x86, 0xe5, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x21, 0x0b, 0x09, 0x89, 0x70, 0xb1, 0x82, 0x95, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0,
	0x04, 0x41, 0x38, 0x4e, 0xb6, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91,
	0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5,
	0xec, 0x1a, 0xe6, 0x1b, 0x0c, 0xb2, 0xd5, 0x19, 0xec, 0xd4, 0x0a, 0x34, 0xa7, 0x97, 0x54, 0x16,
	0xa4, 0x16, 0x27, 0xb1, 0x81, 0xdd, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x21, 0xeb,
	0x16, 0xe6, 0x00, 0x00, 0x00,
}

func (m *Blockstoragestate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Blockstoragestate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Blockstoragestate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintBlockstoragestate(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Blocknumber) > 0 {
		i -= len(m.Blocknumber)
		copy(dAtA[i:], m.Blocknumber)
		i = encodeVarintBlockstoragestate(dAtA, i, uint64(len(m.Blocknumber)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBlockstoragestate(dAtA []byte, offset int, v uint64) int {
	offset -= sovBlockstoragestate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Blockstoragestate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Blocknumber)
	if l > 0 {
		n += 1 + l + sovBlockstoragestate(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovBlockstoragestate(uint64(m.State))
	}
	return n
}

func sovBlockstoragestate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBlockstoragestate(x uint64) (n int) {
	return sovBlockstoragestate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Blockstoragestate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlockstoragestate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Blockstoragestate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Blockstoragestate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blocknumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockstoragestate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockstoragestate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBlockstoragestate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blocknumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockstoragestate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlockstoragestate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBlockstoragestate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBlockstoragestate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBlockstoragestate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockstoragestate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockstoragestate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBlockstoragestate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBlockstoragestate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBlockstoragestate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBlockstoragestate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBlockstoragestate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBlockstoragestate = fmt.Errorf("proto: unexpected end of group")
)
